# Generated by Django 4.2.19 on 2025-02-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_uygulama', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='director_cast',
            field=models.ManyToManyField(blank=True, null=True, related_name='director_cast', to='movie_uygulama.director'),
        ),
    ]
