import pandas as pd
data = [
    ("Suggest me some genres.", 1),
    ("Give me some genres.", 1),
    ("Give some categories.", 1),
    ("Recommend some genres.", 1),
    ("Recommend some categories.", 1),
    ("Suggest some categories.", 1),
    ("Suggest some genres.", 1),
    ("What are some genres?", 1),
    ("What are some categories?", 1),
    ("What genres do you have?", 1),
    ("What categories do you have?", 1),
    ("What genres can you recommend?", 1),
    ("What categories can you recommend?", 1),
    ("What genres do you recommend?", 1),
    ("What categories do you recommend?", 1),
    ("Recommend a few film categories.", 1),
    ("List diverse movie genres.", 1),
    ("I don't know what to watch. Can you suggest a genre?", 1),
    ("Could you provide a selection of series types?", 1),
    ("I need suggestions for cinematic styles.", 1),
    ("What film genre options do you have?", 1),
    ("Please advise on a variety of TV show categories.", 1),
    ("Offer me some unique movie genres.", 1),
    ("Show me different film category choices.", 1),
    ("Tell me some interesting series genres.", 1),
    ("Propose several entertainment types.", 1),
    ("I would like recommendations for film genres.", 1),
    ("Provide me with a list of movie categories.", 1),
    ("Suggest alternative TV show genres.", 1),
    ("List some fresh cinematic categories.", 1),
    ("Recommend a range of film styles.", 1),
    ("Could you list various movie genre options?", 1),
    ("What are some alternative film category ideas?", 1),
    ("I need some creative genre suggestions.", 1),
    ("Offer some innovative movie genres.", 1),
    ("Please supply a variety of series categories.", 1),
    ("Advise me on distinctive film genre choices.", 1),
    ("List out unique entertainment genres.", 1),
    ("What are the available cinematic style options?", 1),
    ("Suggest distinct film categories for me.", 1),
    ("Could you propose innovative TV genres?", 1),
    ("Recommend some varied movie types.", 1),
    ("Please share a selection of film genres.", 1),
    ("I am seeking suggestions for movie categories.", 1),
    ("Tell me some nontraditional series genres.", 1),
    ("Advise on creative film style ideas.", 1),
    ("Propose several unique genre options.", 1),
    ("List some movie genre alternatives.", 1),
    ("What cinematic categories do you recommend?", 1),
    ("Suggest a list of diverse film types.", 1),
    ("Could you provide a range of TV show genres?", 1),
    ("I need a selection of innovative film categories.", 1),
    ("Offer some creative movie genre suggestions.", 1),
    ("Please list different cinematic styles.", 1),
    ("Recommend some original film categories.", 1),
    ("What are some fresh TV show genres?", 1),
    ("Provide innovative genre options for movies.", 1),
    ("Suggest a few alternative film types.", 1),
    ("I would like a variety of series genre recommendations.", 1),
    ("List creative entertainment categories.", 1),
    ("Advise me on alternative cinematic styles.", 1),
    ("Could you suggest nontraditional movie genres?", 1),
    ("What film category options are available?", 1),
    ("Please offer a range of TV show genres.", 1),
    ("Recommend unique movie genre ideas.", 1),
    ("Show me different film style alternatives.", 1),
    ("Tell me some innovative cinematic categories.", 1),
    ("Propose creative movie types.", 1),
    ("I need unique series genre suggestions.", 1),
    ("List assorted film category options.", 1),
    ("What are some distinct movie genres?", 1),
    ("Advise on a variety of film types.", 1),
    ("Could you recommend some original TV genres?", 1),
    ("Suggest nontraditional cinematic categories.", 1),
    ("Provide a list of fresh film genres.", 1),
    ("Offer alternative movie category ideas.", 1),
    ("Please supply creative series genre options.", 1),
    ("What are some innovative film style choices?", 1),
    ("List several distinct movie types.", 1),
    ("Recommend diverse TV show categories.", 1),
    ("Tell me a range of cinematic genre options.", 1),
    ("Propose alternative entertainment genres.", 1),
    ("I need creative film category recommendations.", 1),
    ("Suggest some varied film genres.", 1),
    ("Could you list innovative movie category ideas?", 1),
    ("What unique TV show genre options do you have?", 1),
    ("Please provide a selection of film styles.", 1),
    ("Advise me on distinct cinematic categories.", 1),
    ("Offer creative movie type suggestions.", 1),
    ("List several nontraditional series genres.", 1),
    ("What are some alternative film genre choices?", 1),
    ("Suggest a range of innovative movie categories.", 1),
    ("Could you propose unique TV show types?", 1),
    ("I need a list of diverse cinematic genres.", 1),
    ("Provide alternative film style options.", 1),
    ("Please suggest varied movie genres.", 1),
    ("Recommend a selection of creative series categories.", 1),
    ("Show me unique film genre alternatives.", 1),
    ("Tell me some innovative movie type ideas.", 1),
    ("Propose a range of distinct cinematic categories.", 1),
    ("I am seeking original film genre suggestions.", 1),
    ("List alternative TV show genre options.", 1),
    ("What creative film style choices are there?", 1),
    ("Advise on assorted movie genre recommendations.", 1),
    ("Could you provide innovative series categories?", 1),
    ("Suggest a variety of alternative film genres.", 1),
    ("Please offer distinct movie category options.", 1),
    ("Recommend creative TV show genre ideas.", 1),
    ("List nontraditional cinematic style alternatives.", 1),
    ("What are some unique movie type choices?", 1),
    ("Advise me on a selection of film genres.", 1),
    ("Could you propose alternative entertainment categories?", 1),
    ("I need creative and diverse movie genre ideas.", 1),
    ("Provide a list of innovative film categories.", 1),
    ("Suggest varied series genre options.", 1),

    ("Curiosity led me to explore unknown paths.", 0),
    ("Yesterday, rain poured unexpectedly.", 0),
    ("Beneath the old oak tree, secrets whispered softly.", 0),
    ("Unexpected laughter filled an empty room.", 0),
    ("Sunlight danced on rippling water.", 0),
    ("Wind howled through an abandoned alley.", 0),
    ("Music resonated deeply within every note.", 0),
    ("Moments of silence spoke louder than words.", 0),
    ("Shadows merged as dusk approached swiftly.", 0),
    ("Gentle raindrops created a soothing melody.", 0),
    ("Mystery enveloped a quaint village at midnight.", 0),
    ("Embers glowed faintly in a cooling fire.", 0),
    ("Laughter echoed in a lively marketplace.", 0),
    ("Dreams unfolded like petals in spring.", 0),
    ("Hope emerged amidst challenging times.", 0),
    ("Vibrant colors burst across an urban skyline.", 0),
    ("Silence wrapped the room in peaceful calm.", 0),
    ("Thunder rumbled across distant hills.", 0),
    ("Soft whispers traveled on an evening breeze.", 0),
    ("Stars shimmered over a quiet countryside.", 0),
    ("Midnight unveiled mysteries hidden in plain sight.", 0),
    ("Footsteps echoed in empty corridors.", 0),
    ("Breezes carried the scent of blooming jasmine.", 0),
    ("Waves crashed against rugged cliffs.", 0),
    ("Memories surfaced during a long journey.", 0),
    ("Courage sparked change in unexpected ways.", 0),
    ("Raindrops raced down a foggy window.", 0),
    ("Fireflies illuminated a dark summer night.", 0),
    ("Colors blended seamlessly in a sunset sky.", 0),
    ("Reflections in a quiet lake revealed hidden depths.", 0),
    ("Energy surged through a crowded street.", 0),
    ("Silhouettes moved gracefully against twilight.", 0),
    ("Sudden gust scattered fallen leaves.", 0),
    ("Mystical fog enveloped a silent town.", 0),
    ("Inspiration struck at a moment of despair.", 0),
    ("Curled pages of an old book told ancient stories.", 0),
    ("Time seemed to slow during a gentle snowfall.", 0),
    ("Astonishment filled onlookers during the magic trick.", 0),
    ("Beyond the horizon, dreams awaited discovery.", 0),
    ("Whispers of legends floated on a cool breeze.", 0),
    ("Roaring laughter erupted in a crowded hall.", 0),
    ("Frozen moments captured the essence of time.", 0),
    ("Mystery shrouded long-forgotten ruins.", 0),
    ("Luminous beams cut through a dark forest.", 0),
    ("Bold adventurers embarked on a daring quest.", 0),
    ("Gentle streams meandered through rugged terrain.", 0),
    ("Vast deserts held secrets beneath shifting sands.", 0),
    ("Quiet determination fueled every step.", 0),
    ("Flames flickered against a cold night.", 0),
    ("Intricate frost patterns decorated the window.", 0),
    ("Delight sparkled in the eyes of a curious child.", 0),
    ("Unexpected kindness brightened a gloomy day.", 0),
    ("Reflections on still water revealed a calm soul.", 0),
    ("Passion ignited as the music swelled.", 0),
    ("Mystic voices murmured in an ancient hall.", 0),
    ("Serene landscapes offered solace to wandering minds.", 0),
    ("Bold colors splashed across the dusk canvas.", 0),
    ("Curiosity drove explorers into uncharted territories.", 0),
    ("Humor eased the tension in a stuffy room.", 0),
    ("Dynamic energy radiated from a vibrant crowd.", 0),
    ("Wistful memories lingered in a quiet attic.", 0),
    ("Radiant beams of light danced on calm water.", 0),
    ("Enigmatic symbols decorated a forgotten wall.", 0),
    ("Starlight guided travelers through the dark night.", 0),
    ("Eager anticipation filled the air before the show.", 0),
    ("Murmurs of excitement echoed in a busy gallery.", 0),
    ("Silent rain fell on bustling streets.", 0),
    ("Bold aspirations drove the team forward.", 0),
    ("Soft hues colored an early morning sky.", 0),
    ("Vibrant energy animated a lively festival.", 0),
    ("Unexpected turns made the journey exhilarating.", 0),
    ("Mellow tunes drifted from an open window.", 0),
    ("Quiet contemplation marked the end of the day.", 0),
    ("Serene melodies soothed restless minds.", 0),
    ("Mystical shadows played upon ancient walls.", 0),
    ("Bright sparks of creativity lit up a workshop.", 0),
    ("Twilight embraced the city in a soft glow.", 0),
    ("Curious eyes observed a changing world.", 0),
    ("Gentle rains nurtured budding flowers.", 0),
    ("Brilliance emerged from chaotic moments.", 0),
    ("Enthusiasm surged as the crowd cheered.", 0),
    ("Quiet footsteps trod softly on worn paths.", 0),
    ("Layers of mystery unfolded over time.", 0),
    ("Vivid dreams painted a surreal picture.", 0),
    ("Radiant smiles spread warmth among strangers.", 0),
    ("Calm waters mirrored a vast sky above.", 0),
    ("Dynamic rhythms pulsed through busy streets.", 0),
    ("Delicate petals drifted in a cool evening breeze.", 0),
    ("Serene thoughts mingled with the scent of pine.", 0),
    ("Winds carried distant echoes of laughter.", 0),
    ("Soft shadows danced on colorful pavement.", 0),
    ("Mystic dreams wove tales of forgotten lore.", 0),
    ("Whimsical patterns emerged in swirling fog.", 0),
    ("Harmonious tunes blended with nature's own sounds.", 0),
    ("Unexpected encounters sparked moments of joy.", 0),
    ("Quiet resolve carried her through challenges.", 0),
    ("Auroras lit up polar skies with radiant colors.", 0),
    ("Fleeting moments captured the essence of life.", 0),
    ("Adventures beckoned beyond familiar borders.", 0),
    ("Vivid memories wove the tapestry of time.", 0)
]


df = pd.DataFrame(data, columns=["sentence", "label"])
df.to_csv("cleaned_data3.csv", index=False, encoding="utf-8")
print("CSV başarıyla kaydedildi!")